on:
  push:
    branches:
      - master
      - main
  pull_request: {}

name: Test

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - run: cargo fmt --check
      - run: cargo test
      - run: cargo test --release
      - run: ./try.sh
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo package --allow-dirty
